version: "3.8"

services:
  rembg:
    build: .
    volumes:
      - /Volumes/T7_shield/CryptoVision/Data/Images/Sources/Lab/SJB/Processed/Species/v241226.1/images:/app/input
      - /Volumes/T7_shield/CryptoVision/Data/Images/Sources/Lab/SJB/Processed/Species/v241226.1/nobg:/app/output
      #- ~/.u2net:/root/.u2net  # Persist the u2net model download
    environment:
      - INPUT_PATH=/app/input
      - OUTPUT_PATH=/app/output
    command: ["--input", "/app/input", "--output", "/app/output"]
