seed: 42
verbose: false
version: auto  
project: "CVisionClassifier"
pretrain: "rn50v2"                 # rn50v2 |  rn152v2 | efv2b0 | efv2b1 | vgg16
save: true
fine_tune: False
image_size: 224

# Warning
suppress_warnings: true

name: "CVision_BasicV2"
tags: ['IMGSZ128','SRD2048','DP04']

# Data
test_size: 0.15
validation_size: 0.15
batch_size: 32
samples_threshold: 90

# Model
cvision_model: basic           
dropout: 0.4
shared_layer_neurons: 2048      # 256 | 512 | 1024 | 2048

# Compile
lr: 0.0001
loss: "categorical_focal_crossentropy"
metrics: ["accuracy", "Precision", "Recall", "AUC"]
loss_weights: [1.0, 1.5, 2.0]

# Training
epochs: 10

# Early stopping
patience: 3
early_stop_monitor: "val_loss"
restore_best_weights: true

# Reduce learning rate
reduce_lr_monitor: "val_loss"
lr_factor: 0.2
lr_patience: 2
lr_min: 0.000001

# Checkpoint
checkpoint_monitor: "val_loss"
save_best_only: true
checkpoint_mode: "min"

# Fine-tuning
ftune:
  epochs: 20
  layers: 15
  lr: 0.00001
  patience: 4
  loss: "categorical_focal_crossentropy"
  metrics: ["accuracy", "Precision", "Recall", "AUC"]
  loss_weights: [1.0, 1.5, 2.0]
  checkpoint_monitor: "val_loss"
  save_best_only: true

grid_search:
  features_dropout: [0, 0.2, 0.3, 0.4]
  shared_dropout: [0, 0.2, 0.3, 0.4]
  shared_layer_neurons: [512, 1024, 2048]
  pooling_type: ["avg", "max"]
  concat: [True, False]
  loss_weights: [[1.0, 1.5, 2.0], [1.0, 1.0, 1.0]]